version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build Started...
      - chmod +x ./gradlew
      - ./gradlew build
artifacts:
  files:
    - build/libs/*.jar